version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5445:5432'
    environment:
      - POSTGRES_USER=buildfit
      - POSTGRES_PASSWORD=buildfit
      - POSTGRES_DB=buildfit
    volumes:
      - buildfit_pg_data:/bitnami/postgresql

volumes:
  buildfit_pg_data:
